export const ZQUOTER_ABI = [
  { inputs: [], stateMutability: "payable", type: "constructor" },
  { inputs: [], name: "NoRoute", type: "error" },
  { inputs: [], name: "SlippageBpsTooHigh", type: "error" },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "address", name: "tokenIn", type: "address" },
      { internalType: "address", name: "tokenOut", type: "address" },
      { internalType: "uint256", name: "swapAmount", type: "uint256" },
      { internalType: "uint256", name: "slippageBps", type: "uint256" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
    ],
    name: "build3HopMulticall",
    outputs: [
      {
        components: [
          { internalType: "enum zQuoter.AMM", name: "source", type: "uint8" },
          { internalType: "uint256", name: "feeBps", type: "uint256" },
          { internalType: "uint256", name: "amountIn", type: "uint256" },
          { internalType: "uint256", name: "amountOut", type: "uint256" },
        ],
        internalType: "struct zQuoter.Quote",
        name: "a",
        type: "tuple",
      },
      {
        components: [
          { internalType: "enum zQuoter.AMM", name: "source", type: "uint8" },
          { internalType: "uint256", name: "feeBps", type: "uint256" },
          { internalType: "uint256", name: "amountIn", type: "uint256" },
          { internalType: "uint256", name: "amountOut", type: "uint256" },
        ],
        internalType: "struct zQuoter.Quote",
        name: "b",
        type: "tuple",
      },
      {
        components: [
          { internalType: "enum zQuoter.AMM", name: "source", type: "uint8" },
          { internalType: "uint256", name: "feeBps", type: "uint256" },
          { internalType: "uint256", name: "amountIn", type: "uint256" },
          { internalType: "uint256", name: "amountOut", type: "uint256" },
        ],
        internalType: "struct zQuoter.Quote",
        name: "c",
        type: "tuple",
      },
      { internalType: "bytes[]", name: "calls", type: "bytes[]" },
      { internalType: "bytes", name: "multicall", type: "bytes" },
      { internalType: "uint256", name: "msgValue", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "bool", name: "exactOut", type: "bool" },
      { internalType: "address", name: "tokenIn", type: "address" },
      { internalType: "address", name: "tokenOut", type: "address" },
      { internalType: "uint256", name: "swapAmount", type: "uint256" },
      { internalType: "uint256", name: "slippageBps", type: "uint256" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
    ],
    name: "buildBestSwap",
    outputs: [
      {
        components: [
          { internalType: "enum zQuoter.AMM", name: "source", type: "uint8" },
          { internalType: "uint256", name: "feeBps", type: "uint256" },
          { internalType: "uint256", name: "amountIn", type: "uint256" },
          { internalType: "uint256", name: "amountOut", type: "uint256" },
        ],
        internalType: "struct zQuoter.Quote",
        name: "best",
        type: "tuple",
      },
      { internalType: "bytes", name: "callData", type: "bytes" },
      { internalType: "uint256", name: "amountLimit", type: "uint256" },
      { internalType: "uint256", name: "msgValue", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "address", name: "refundTo", type: "address" },
      { internalType: "bool", name: "exactOut", type: "bool" },
      { internalType: "address", name: "tokenIn", type: "address" },
      { internalType: "address", name: "tokenOut", type: "address" },
      { internalType: "uint256", name: "swapAmount", type: "uint256" },
      { internalType: "uint256", name: "slippageBps", type: "uint256" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
      { internalType: "uint24", name: "hookPoolFee", type: "uint24" },
      { internalType: "int24", name: "hookTickSpacing", type: "int24" },
      { internalType: "address", name: "hookAddress", type: "address" },
    ],
    name: "buildBestSwapViaETHMulticall",
    outputs: [
      {
        components: [
          { internalType: "enum zQuoter.AMM", name: "source", type: "uint8" },
          { internalType: "uint256", name: "feeBps", type: "uint256" },
          { internalType: "uint256", name: "amountIn", type: "uint256" },
          { internalType: "uint256", name: "amountOut", type: "uint256" },
        ],
        internalType: "struct zQuoter.Quote",
        name: "a",
        type: "tuple",
      },
      {
        components: [
          { internalType: "enum zQuoter.AMM", name: "source", type: "uint8" },
          { internalType: "uint256", name: "feeBps", type: "uint256" },
          { internalType: "uint256", name: "amountIn", type: "uint256" },
          { internalType: "uint256", name: "amountOut", type: "uint256" },
        ],
        internalType: "struct zQuoter.Quote",
        name: "b",
        type: "tuple",
      },
      { internalType: "bytes[]", name: "calls", type: "bytes[]" },
      { internalType: "bytes", name: "multicall", type: "bytes" },
      { internalType: "uint256", name: "msgValue", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "address", name: "tokenIn", type: "address" },
      { internalType: "address", name: "tokenOut", type: "address" },
      { internalType: "uint256", name: "swapAmount", type: "uint256" },
      { internalType: "uint256", name: "slippageBps", type: "uint256" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
    ],
    name: "buildHybridSplit",
    outputs: [
      {
        components: [
          { internalType: "enum zQuoter.AMM", name: "source", type: "uint8" },
          { internalType: "uint256", name: "feeBps", type: "uint256" },
          { internalType: "uint256", name: "amountIn", type: "uint256" },
          { internalType: "uint256", name: "amountOut", type: "uint256" },
        ],
        internalType: "struct zQuoter.Quote[2]",
        name: "legs",
        type: "tuple[2]",
      },
      { internalType: "bytes", name: "multicall", type: "bytes" },
      { internalType: "uint256", name: "msgValue", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "address", name: "tokenIn", type: "address" },
      { internalType: "address", name: "tokenOut", type: "address" },
      { internalType: "uint256", name: "swapAmount", type: "uint256" },
      { internalType: "uint256", name: "slippageBps", type: "uint256" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
    ],
    name: "buildSplitSwap",
    outputs: [
      {
        components: [
          { internalType: "enum zQuoter.AMM", name: "source", type: "uint8" },
          { internalType: "uint256", name: "feeBps", type: "uint256" },
          { internalType: "uint256", name: "amountIn", type: "uint256" },
          { internalType: "uint256", name: "amountOut", type: "uint256" },
        ],
        internalType: "struct zQuoter.Quote[2]",
        name: "legs",
        type: "tuple[2]",
      },
      { internalType: "bytes", name: "multicall", type: "bytes" },
      { internalType: "uint256", name: "msgValue", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "address", name: "tokenIn", type: "address" },
      { internalType: "address", name: "tokenOut", type: "address" },
      { internalType: "uint256", name: "swapAmount", type: "uint256" },
      { internalType: "uint256", name: "slippageBps", type: "uint256" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
      { internalType: "uint24", name: "hookPoolFee", type: "uint24" },
      { internalType: "int24", name: "hookTickSpacing", type: "int24" },
      { internalType: "address", name: "hookAddress", type: "address" },
    ],
    name: "buildSplitSwapHooked",
    outputs: [
      {
        components: [
          { internalType: "enum zQuoter.AMM", name: "source", type: "uint8" },
          { internalType: "uint256", name: "feeBps", type: "uint256" },
          { internalType: "uint256", name: "amountIn", type: "uint256" },
          { internalType: "uint256", name: "amountOut", type: "uint256" },
        ],
        internalType: "struct zQuoter.Quote[2]",
        name: "legs",
        type: "tuple[2]",
      },
      { internalType: "bytes", name: "multicall", type: "bytes" },
      { internalType: "uint256", name: "msgValue", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bool", name: "exactOut", type: "bool" },
      { internalType: "address", name: "tokenIn", type: "address" },
      { internalType: "address", name: "tokenOut", type: "address" },
      { internalType: "uint256", name: "swapAmount", type: "uint256" },
    ],
    name: "getQuotes",
    outputs: [
      {
        components: [
          { internalType: "enum zQuoter.AMM", name: "source", type: "uint8" },
          { internalType: "uint256", name: "feeBps", type: "uint256" },
          { internalType: "uint256", name: "amountIn", type: "uint256" },
          { internalType: "uint256", name: "amountOut", type: "uint256" },
        ],
        internalType: "struct zQuoter.Quote",
        name: "best",
        type: "tuple",
      },
      {
        components: [
          { internalType: "enum zQuoter.AMM", name: "source", type: "uint8" },
          { internalType: "uint256", name: "feeBps", type: "uint256" },
          { internalType: "uint256", name: "amountIn", type: "uint256" },
          { internalType: "uint256", name: "amountOut", type: "uint256" },
        ],
        internalType: "struct zQuoter.Quote[]",
        name: "quotes",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bool", name: "exactOut", type: "bool" },
      { internalType: "address", name: "tokenIn", type: "address" },
      { internalType: "address", name: "tokenOut", type: "address" },
      { internalType: "uint256", name: "swapAmount", type: "uint256" },
      { internalType: "uint256", name: "maxCandidates", type: "uint256" },
    ],
    name: "quoteCurve",
    outputs: [
      { internalType: "uint256", name: "amountIn", type: "uint256" },
      { internalType: "uint256", name: "amountOut", type: "uint256" },
      { internalType: "address", name: "bestPool", type: "address" },
      { internalType: "bool", name: "usedUnderlying", type: "bool" },
      { internalType: "bool", name: "usedStable", type: "bool" },
      { internalType: "uint8", name: "iIndex", type: "uint8" },
      { internalType: "uint8", name: "jIndex", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bool", name: "exactOut", type: "bool" },
      { internalType: "address", name: "tokenOut", type: "address" },
      { internalType: "uint256", name: "swapAmount", type: "uint256" },
    ],
    name: "quoteLido",
    outputs: [
      { internalType: "uint256", name: "amountIn", type: "uint256" },
      { internalType: "uint256", name: "amountOut", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const
